# List of plugins
set -g @tpm_plugins '                     \
    caiogondim/maglev                     \
    tmux-plugins/tpm                      \
    tmux-plugins/tmux-sensible            \
    tmux-plugins/tmux-yank                \
    tmux-plugins/tmux-pain-control        \
    tmux-plugins/tmux-prefix-highlight    \
    christoomey/vim-tmux-navigator        \
'

# Stay in copy mode after yanking
set -g @yank_action 'copy-pipe-no-clear'

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# general
set -g base-index 1
set -g pane-base-index 1
set -g history-limit 2000
set -g repeat-time 0
set -g set-clipboard on
set -g renumber-windows on
setw -g mouse on
setw -g wrap-search off
setw -g xterm-keys on
set -g default-terminal "tmux-256color"

# cursor shape support (thin cursor like in Ghostty)
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# reduce escape-time for better responsiveness and animations
set -sg escape-time 0

# key binding
unbind , # rename window
unbind . # move window
bind , previous-window
bind . next-window
unbind [ # enter copy mode
unbind ] # paste buffer
unbind v
unbind p
bind v copy-mode
bind p paste-buffer
bind n command-prompt -p "Pane name:" "select-pane -T '%%'"
bind -Tcopy-mode-vi 'v' send -X begin-selection
bind -Tcopy-mode-vi 'y' send -X copy-pipe-no-clear "reattach-to-user-namespace pbcopy"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
