name: 6billing-admin
root: ~/src/billing-admin/

on_project_start: if [ $(git rev-parse --abbrev-ref HEAD) == "master" ]; then git pl; fi

startup_window: shell

pre_window: nvm use

windows:
  - server:
      layout: even-horizontal
      panes:
        - yarn && yarn start
        - git fetch
  - shell:
