name: 22dofus-elevage-app
root: ~/Projects/web-apps/dofus-elevage-app

startup_window: editor

pre_window:
  - nvm use

windows:
  - server:
      layout: even-horizontal
      panes:
        - ember serve
        - git fetch
  - editor: vim
  - test:
