name: 11dofus-elevage
root: ~/Projects/web-apps/dofus-elevage

on_project_stop:
  - docker-compose down

startup_window: editor

windows:
  - server:
      layout: even-horizontal
      panes:
        - rails s -p 9000
        - docker-compose up
  - console:
      layout: even-vertical
      panes:
        - wait-port localhost:9000 && rails c
        - git fetch
  - editor: vim
  - test:
