name: 1intercom
root: ~/src/intercom

on_project_stop:
  - pilot stop intercom

startup_window: editor

windows:
  - console: pilot start --no-log nexus-relay nexus-go
  - server: pilot start intercom
  - editor: vim
  - test:
