name: 4intercom-integrations
root: ~/src/intercom-integrations

on_project_start: if [ $(git rev-parse --abbrev-ref HEAD) == "master" ]; then git pl; fi

on_project_stop:
  - echo "Killing dangling process" && pkill -9 -f "puma.*\[intercom-integrations\]"
  - pilot stop eagle

startup_window: editor

windows:
  - server: script/update && script/server
  - console:
      layout: even-vertical
      panes:
        - wait-port localhost:3040 && script/console
        - git fetch
  - editor: vim
  - test:
