name: 2intercom-js
root: ~/src/intercom-js

pre_window:
  - nvm use

on_project_stop:
  - pilot stop intercom-js

startup_window: editor

windows:
  - server: pilot start intercom-js
  - editor: vim
  - test:
