name: 1intercom
root: ~/src/intercom

on_project_start: if [ $(git rev-parse --abbrev-ref HEAD) == "master" ]; then git pl; fi

on_project_stop:
  - echo "Killing dangling process" && pkill -9 -f "puma.*\[intercom\]"
  - pilot stop elasticsearch-6 mysql redis memcached dynamodb mongodb nexus-go nexus-relay nexus-redis nexus-go-long-poller

startup_window: editor

windows:
  - console:
      layout: even-vertical
      panes:
        - wait-port localhost:3000 && script/console
        - pilot start --no-log nexus-relay nexus-go && git fetch
  - server: script/update && script/server
  - editor: vim
  - test:
