name: 0recipe-app
root: ~/Projects/web-apps/my-recipe-box-app

on_project_start: if [ $(git rev-parse --abbrev-ref HEAD) == "master" ]; then git pl; fi

pre_window:
  - nvm use

startup_window: editor

windows:
  - server:
      layout: even-horizontal
      panes:
        - yarn && yarn start
        - git fetch
  - editor: vim
  - test:
