# Catppuccin Frappe palette
palette = "catppuccin_frappe"

format = """
[](surface0)\
$time\
[](bg:blue fg:surface0)\
$directory\
[](fg:blue bg:lavender)\
$git_branch\
$git_status\
[](fg:lavender bg:surface0)\
$nodejs\
$ruby\
$golang\
$rust\
$python\
[](fg:surface0)\
$cmd_duration\
$character"""

[time]
disabled = false
time_format = "%R"
style = "bg:surface0 fg:text"
format = '[ $time ]($style)'

[directory]
style = "bg:blue fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:lavender fg:crust"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:lavender fg:crust"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:surface0 fg:green"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:surface0 fg:red"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:surface0 fg:blue"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:surface0 fg:peach"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:surface0 fg:yellow"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 500
format = "[ 󱎫 $duration]($style) "
style = "yellow"

[character]
success_symbol = " [](green)"
error_symbol = " [](red)"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
